name: Sync Fork on Push

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        run: |
          git clone https://x-access-token:${{ secrets.FORK_SYNC_TOKEN }}@github.com/kayzama/GR27.git
          cd GR27
          git remote add upstream https://github.com/KLTN-03-2026/GR27.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main